apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-stockfinder-clearurl
  namespace: stockfinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-stockfinder-clearurl
  template:
    metadata:
      labels:
        app: k3s-stockfinder-clearurl
    spec:
      containers:
        - name: k3s-stockfinder-clearurl
          image: ghcr.io/mdaniel592/stockfinder-clearurl:main
          env:
          - name: TELEGRAM_TOKEN
            valueFrom:
              secretKeyRef:
                name: nvidia-telegram-token
                key: telegram-token
          - name: TELEGRAM_CHANNEL
            valueFrom:
              secretKeyRef:
                name: nvidia-telegram-channel
                key: telegram-channel
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.01
              memory: 25Mi
            limits:
              cpu: 0.1
              memory: 50Mi

      imagePullSecrets:
        - name: ghcr-login-secret
